name: simple-tensor
synopsis: Simple type-safe tensors
maintainer: Michael Kareithi
license: MIT

dependencies:
  - base
  - vector
  - reflection
  
library:
  source-dirs: src
  exposed-modules:
    - Data.Simple.Tensor
    
